// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: internal/codec/codec.proto

package codec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum equivalent to your ValueType string constants
type ValueType int32

const (
	// Note: Proto3 enums must start with 0
	ValueType_VALUE_TYPE_UNSPECIFIED ValueType = 0 // Default/unknown value
	ValueType_INT_VALUE_TYPE         ValueType = 1
	ValueType_STRING_VALUE_TYPE      ValueType = 2
	ValueType_BYTES_VALUE_TYPE       ValueType = 3
	ValueType_FLOAT_VALUE_TYPE       ValueType = 4
	ValueType_NUMERIC_VALUE_TYPE     ValueType = 5
	ValueType_BIG_NUMERIC_VALUE_TYPE ValueType = 6
	ValueType_BOOL_VALUE_TYPE        ValueType = 7
	ValueType_JSON_VALUE_TYPE        ValueType = 8
	ValueType_ARRAY_VALUE_TYPE       ValueType = 9
	ValueType_STRUCT_VALUE_TYPE      ValueType = 10
	ValueType_DATE_VALUE_TYPE        ValueType = 11
	ValueType_DATETIME_VALUE_TYPE    ValueType = 12
	ValueType_TIME_VALUE_TYPE        ValueType = 13
	ValueType_TIMESTAMP_VALUE_TYPE   ValueType = 14
	ValueType_INTERVAL_VALUE_TYPE    ValueType = 15
)

// Enum value maps for ValueType.
var (
	ValueType_name = map[int32]string{
		0:  "VALUE_TYPE_UNSPECIFIED",
		1:  "INT_VALUE_TYPE",
		2:  "STRING_VALUE_TYPE",
		3:  "BYTES_VALUE_TYPE",
		4:  "FLOAT_VALUE_TYPE",
		5:  "NUMERIC_VALUE_TYPE",
		6:  "BIG_NUMERIC_VALUE_TYPE",
		7:  "BOOL_VALUE_TYPE",
		8:  "JSON_VALUE_TYPE",
		9:  "ARRAY_VALUE_TYPE",
		10: "STRUCT_VALUE_TYPE",
		11: "DATE_VALUE_TYPE",
		12: "DATETIME_VALUE_TYPE",
		13: "TIME_VALUE_TYPE",
		14: "TIMESTAMP_VALUE_TYPE",
		15: "INTERVAL_VALUE_TYPE",
	}
	ValueType_value = map[string]int32{
		"VALUE_TYPE_UNSPECIFIED": 0,
		"INT_VALUE_TYPE":         1,
		"STRING_VALUE_TYPE":      2,
		"BYTES_VALUE_TYPE":       3,
		"FLOAT_VALUE_TYPE":       4,
		"NUMERIC_VALUE_TYPE":     5,
		"BIG_NUMERIC_VALUE_TYPE": 6,
		"BOOL_VALUE_TYPE":        7,
		"JSON_VALUE_TYPE":        8,
		"ARRAY_VALUE_TYPE":       9,
		"STRUCT_VALUE_TYPE":      10,
		"DATE_VALUE_TYPE":        11,
		"DATETIME_VALUE_TYPE":    12,
		"TIME_VALUE_TYPE":        13,
		"TIMESTAMP_VALUE_TYPE":   14,
		"INTERVAL_VALUE_TYPE":    15,
	}
)

func (x ValueType) Enum() *ValueType {
	p := new(ValueType)
	*p = x
	return p
}

func (x ValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_codec_codec_proto_enumTypes[0].Descriptor()
}

func (ValueType) Type() protoreflect.EnumType {
	return &file_internal_codec_codec_proto_enumTypes[0]
}

func (x ValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueType.Descriptor instead.
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return file_internal_codec_codec_proto_rawDescGZIP(), []int{0}
}

// Equivalent to your ValueLayout struct
type ValueLayout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        ValueType              `protobuf:"varint,1,opt,name=header,proto3,enum=codec.ValueType" json:"header,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueLayout) Reset() {
	*x = ValueLayout{}
	mi := &file_internal_codec_codec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueLayout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueLayout) ProtoMessage() {}

func (x *ValueLayout) ProtoReflect() protoreflect.Message {
	mi := &file_internal_codec_codec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueLayout.ProtoReflect.Descriptor instead.
func (*ValueLayout) Descriptor() ([]byte, []int) {
	return file_internal_codec_codec_proto_rawDescGZIP(), []int{0}
}

func (x *ValueLayout) GetHeader() ValueType {
	if x != nil {
		return x.Header
	}
	return ValueType_VALUE_TYPE_UNSPECIFIED
}

func (x *ValueLayout) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// Equivalent to your StructValueLayout struct
// Since proto doesn't have interface{}, we use Any for flexible values
type StructValueLayout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Values        []*ValueLayout         `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructValueLayout) Reset() {
	*x = StructValueLayout{}
	mi := &file_internal_codec_codec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructValueLayout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructValueLayout) ProtoMessage() {}

func (x *StructValueLayout) ProtoReflect() protoreflect.Message {
	mi := &file_internal_codec_codec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructValueLayout.ProtoReflect.Descriptor instead.
func (*StructValueLayout) Descriptor() ([]byte, []int) {
	return file_internal_codec_codec_proto_rawDescGZIP(), []int{1}
}

func (x *StructValueLayout) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *StructValueLayout) GetValues() []*ValueLayout {
	if x != nil {
		return x.Values
	}
	return nil
}

// Alternative approach using oneof for type-safe values
// This is more protobuf-idiomatic than using Any
type TypedValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*TypedValue_IntValue
	//	*TypedValue_StringValue
	//	*TypedValue_BytesValue
	//	*TypedValue_FloatValue
	//	*TypedValue_NumericValue
	//	*TypedValue_BigNumericValue
	//	*TypedValue_BoolValue
	//	*TypedValue_JsonValue
	//	*TypedValue_ArrayValue
	//	*TypedValue_StructValue
	//	*TypedValue_DateValue
	//	*TypedValue_DatetimeValue
	//	*TypedValue_TimeValue
	//	*TypedValue_TimestampValue
	//	*TypedValue_IntervalValue
	Value         isTypedValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypedValue) Reset() {
	*x = TypedValue{}
	mi := &file_internal_codec_codec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypedValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypedValue) ProtoMessage() {}

func (x *TypedValue) ProtoReflect() protoreflect.Message {
	mi := &file_internal_codec_codec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypedValue.ProtoReflect.Descriptor instead.
func (*TypedValue) Descriptor() ([]byte, []int) {
	return file_internal_codec_codec_proto_rawDescGZIP(), []int{2}
}

func (x *TypedValue) GetValue() isTypedValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *TypedValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *TypedValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *TypedValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *TypedValue) GetFloatValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *TypedValue) GetNumericValue() string {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_NumericValue); ok {
			return x.NumericValue
		}
	}
	return ""
}

func (x *TypedValue) GetBigNumericValue() string {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_BigNumericValue); ok {
			return x.BigNumericValue
		}
	}
	return ""
}

func (x *TypedValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *TypedValue) GetJsonValue() string {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_JsonValue); ok {
			return x.JsonValue
		}
	}
	return ""
}

func (x *TypedValue) GetArrayValue() *ArrayValue {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_ArrayValue); ok {
			return x.ArrayValue
		}
	}
	return nil
}

func (x *TypedValue) GetStructValue() *StructValue {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_StructValue); ok {
			return x.StructValue
		}
	}
	return nil
}

func (x *TypedValue) GetDateValue() string {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_DateValue); ok {
			return x.DateValue
		}
	}
	return ""
}

func (x *TypedValue) GetDatetimeValue() string {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_DatetimeValue); ok {
			return x.DatetimeValue
		}
	}
	return ""
}

func (x *TypedValue) GetTimeValue() string {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_TimeValue); ok {
			return x.TimeValue
		}
	}
	return ""
}

func (x *TypedValue) GetTimestampValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_TimestampValue); ok {
			return x.TimestampValue
		}
	}
	return 0
}

func (x *TypedValue) GetIntervalValue() string {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_IntervalValue); ok {
			return x.IntervalValue
		}
	}
	return ""
}

type isTypedValue_Value interface {
	isTypedValue_Value()
}

type TypedValue_IntValue struct {
	IntValue int64 `protobuf:"varint,1,opt,name=int_value,json=intValue,proto3,oneof"`
}

type TypedValue_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type TypedValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,3,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type TypedValue_FloatValue struct {
	FloatValue float64 `protobuf:"fixed64,4,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type TypedValue_NumericValue struct {
	NumericValue string `protobuf:"bytes,5,opt,name=numeric_value,json=numericValue,proto3,oneof"` // Keep as string for precision
}

type TypedValue_BigNumericValue struct {
	BigNumericValue string `protobuf:"bytes,6,opt,name=big_numeric_value,json=bigNumericValue,proto3,oneof"` // Keep as string for precision
}

type TypedValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,7,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type TypedValue_JsonValue struct {
	JsonValue string `protobuf:"bytes,8,opt,name=json_value,json=jsonValue,proto3,oneof"` // JSON as string
}

type TypedValue_ArrayValue struct {
	ArrayValue *ArrayValue `protobuf:"bytes,9,opt,name=array_value,json=arrayValue,proto3,oneof"`
}

type TypedValue_StructValue struct {
	StructValue *StructValue `protobuf:"bytes,10,opt,name=struct_value,json=structValue,proto3,oneof"`
}

type TypedValue_DateValue struct {
	DateValue string `protobuf:"bytes,11,opt,name=date_value,json=dateValue,proto3,oneof"` // ISO date string
}

type TypedValue_DatetimeValue struct {
	DatetimeValue string `protobuf:"bytes,12,opt,name=datetime_value,json=datetimeValue,proto3,oneof"` // ISO datetime string
}

type TypedValue_TimeValue struct {
	TimeValue string `protobuf:"bytes,13,opt,name=time_value,json=timeValue,proto3,oneof"` // ISO time string
}

type TypedValue_TimestampValue struct {
	TimestampValue int64 `protobuf:"varint,14,opt,name=timestamp_value,json=timestampValue,proto3,oneof"` // Unix timestamp
}

type TypedValue_IntervalValue struct {
	IntervalValue string `protobuf:"bytes,15,opt,name=interval_value,json=intervalValue,proto3,oneof"` // ISO 8601 duration
}

func (*TypedValue_IntValue) isTypedValue_Value() {}

func (*TypedValue_StringValue) isTypedValue_Value() {}

func (*TypedValue_BytesValue) isTypedValue_Value() {}

func (*TypedValue_FloatValue) isTypedValue_Value() {}

func (*TypedValue_NumericValue) isTypedValue_Value() {}

func (*TypedValue_BigNumericValue) isTypedValue_Value() {}

func (*TypedValue_BoolValue) isTypedValue_Value() {}

func (*TypedValue_JsonValue) isTypedValue_Value() {}

func (*TypedValue_ArrayValue) isTypedValue_Value() {}

func (*TypedValue_StructValue) isTypedValue_Value() {}

func (*TypedValue_DateValue) isTypedValue_Value() {}

func (*TypedValue_DatetimeValue) isTypedValue_Value() {}

func (*TypedValue_TimeValue) isTypedValue_Value() {}

func (*TypedValue_TimestampValue) isTypedValue_Value() {}

func (*TypedValue_IntervalValue) isTypedValue_Value() {}

// Supporting messages for complex types
type ArrayValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []*TypedValue          `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrayValue) Reset() {
	*x = ArrayValue{}
	mi := &file_internal_codec_codec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrayValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayValue) ProtoMessage() {}

func (x *ArrayValue) ProtoReflect() protoreflect.Message {
	mi := &file_internal_codec_codec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayValue.ProtoReflect.Descriptor instead.
func (*ArrayValue) Descriptor() ([]byte, []int) {
	return file_internal_codec_codec_proto_rawDescGZIP(), []int{3}
}

func (x *ArrayValue) GetElements() []*TypedValue {
	if x != nil {
		return x.Elements
	}
	return nil
}

type StructValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]*TypedValue `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructValue) Reset() {
	*x = StructValue{}
	mi := &file_internal_codec_codec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructValue) ProtoMessage() {}

func (x *StructValue) ProtoReflect() protoreflect.Message {
	mi := &file_internal_codec_codec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructValue.ProtoReflect.Descriptor instead.
func (*StructValue) Descriptor() ([]byte, []int) {
	return file_internal_codec_codec_proto_rawDescGZIP(), []int{4}
}

func (x *StructValue) GetFields() map[string]*TypedValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Type-safe version of StructValueLayout
type TypedStructValueLayout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Values        []*ValueLayout         `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypedStructValueLayout) Reset() {
	*x = TypedStructValueLayout{}
	mi := &file_internal_codec_codec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypedStructValueLayout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypedStructValueLayout) ProtoMessage() {}

func (x *TypedStructValueLayout) ProtoReflect() protoreflect.Message {
	mi := &file_internal_codec_codec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypedStructValueLayout.ProtoReflect.Descriptor instead.
func (*TypedStructValueLayout) Descriptor() ([]byte, []int) {
	return file_internal_codec_codec_proto_rawDescGZIP(), []int{5}
}

func (x *TypedStructValueLayout) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *TypedStructValueLayout) GetValues() []*ValueLayout {
	if x != nil {
		return x.Values
	}
	return nil
}

// If you want to maintain backward compatibility with interface{}
// but still have some type safety, you can use this hybrid approach
type FlexibleValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  ValueType              `protobuf:"varint,1,opt,name=type,proto3,enum=codec.ValueType" json:"type,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*FlexibleValue_IntValue
	//	*FlexibleValue_StringValue
	//	*FlexibleValue_BytesValue
	//	*FlexibleValue_FloatValue
	//	*FlexibleValue_BoolValue
	//	*FlexibleValue_JsonString
	Value         isFlexibleValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlexibleValue) Reset() {
	*x = FlexibleValue{}
	mi := &file_internal_codec_codec_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlexibleValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlexibleValue) ProtoMessage() {}

func (x *FlexibleValue) ProtoReflect() protoreflect.Message {
	mi := &file_internal_codec_codec_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlexibleValue.ProtoReflect.Descriptor instead.
func (*FlexibleValue) Descriptor() ([]byte, []int) {
	return file_internal_codec_codec_proto_rawDescGZIP(), []int{6}
}

func (x *FlexibleValue) GetType() ValueType {
	if x != nil {
		return x.Type
	}
	return ValueType_VALUE_TYPE_UNSPECIFIED
}

func (x *FlexibleValue) GetValue() isFlexibleValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FlexibleValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*FlexibleValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *FlexibleValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*FlexibleValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *FlexibleValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*FlexibleValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *FlexibleValue) GetFloatValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*FlexibleValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *FlexibleValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*FlexibleValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *FlexibleValue) GetJsonString() string {
	if x != nil {
		if x, ok := x.Value.(*FlexibleValue_JsonString); ok {
			return x.JsonString
		}
	}
	return ""
}

type isFlexibleValue_Value interface {
	isFlexibleValue_Value()
}

type FlexibleValue_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type FlexibleValue_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type FlexibleValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,4,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type FlexibleValue_FloatValue struct {
	FloatValue float64 `protobuf:"fixed64,5,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type FlexibleValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,6,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type FlexibleValue_JsonString struct {
	JsonString string `protobuf:"bytes,7,opt,name=json_string,json=jsonString,proto3,oneof"` // For JSON, arrays, structs serialized as strings
}

func (*FlexibleValue_IntValue) isFlexibleValue_Value() {}

func (*FlexibleValue_StringValue) isFlexibleValue_Value() {}

func (*FlexibleValue_BytesValue) isFlexibleValue_Value() {}

func (*FlexibleValue_FloatValue) isFlexibleValue_Value() {}

func (*FlexibleValue_BoolValue) isFlexibleValue_Value() {}

func (*FlexibleValue_JsonString) isFlexibleValue_Value() {}

type FlexibleStructValueLayout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Values        []*FlexibleValue       `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlexibleStructValueLayout) Reset() {
	*x = FlexibleStructValueLayout{}
	mi := &file_internal_codec_codec_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlexibleStructValueLayout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlexibleStructValueLayout) ProtoMessage() {}

func (x *FlexibleStructValueLayout) ProtoReflect() protoreflect.Message {
	mi := &file_internal_codec_codec_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlexibleStructValueLayout.ProtoReflect.Descriptor instead.
func (*FlexibleStructValueLayout) Descriptor() ([]byte, []int) {
	return file_internal_codec_codec_proto_rawDescGZIP(), []int{7}
}

func (x *FlexibleStructValueLayout) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *FlexibleStructValueLayout) GetValues() []*FlexibleValue {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_internal_codec_codec_proto protoreflect.FileDescriptor

const file_internal_codec_codec_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/codec/codec.proto\x12\x05codec\x1a\x19google/protobuf/any.proto\"K\n" +
	"\vValueLayout\x12(\n" +
	"\x06header\x18\x01 \x01(\x0e2\x10.codec.ValueTypeR\x06header\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\"S\n" +
	"\x11StructValueLayout\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\x12*\n" +
	"\x06values\x18\x02 \x03(\v2\x12.codec.ValueLayoutR\x06values\"\xe4\x04\n" +
	"\n" +
	"TypedValue\x12\x1d\n" +
	"\tint_value\x18\x01 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vbytes_value\x18\x03 \x01(\fH\x00R\n" +
	"bytesValue\x12!\n" +
	"\vfloat_value\x18\x04 \x01(\x01H\x00R\n" +
	"floatValue\x12%\n" +
	"\rnumeric_value\x18\x05 \x01(\tH\x00R\fnumericValue\x12,\n" +
	"\x11big_numeric_value\x18\x06 \x01(\tH\x00R\x0fbigNumericValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\a \x01(\bH\x00R\tboolValue\x12\x1f\n" +
	"\n" +
	"json_value\x18\b \x01(\tH\x00R\tjsonValue\x124\n" +
	"\varray_value\x18\t \x01(\v2\x11.codec.ArrayValueH\x00R\n" +
	"arrayValue\x127\n" +
	"\fstruct_value\x18\n" +
	" \x01(\v2\x12.codec.StructValueH\x00R\vstructValue\x12\x1f\n" +
	"\n" +
	"date_value\x18\v \x01(\tH\x00R\tdateValue\x12'\n" +
	"\x0edatetime_value\x18\f \x01(\tH\x00R\rdatetimeValue\x12\x1f\n" +
	"\n" +
	"time_value\x18\r \x01(\tH\x00R\ttimeValue\x12)\n" +
	"\x0ftimestamp_value\x18\x0e \x01(\x03H\x00R\x0etimestampValue\x12'\n" +
	"\x0einterval_value\x18\x0f \x01(\tH\x00R\rintervalValueB\a\n" +
	"\x05value\";\n" +
	"\n" +
	"ArrayValue\x12-\n" +
	"\belements\x18\x01 \x03(\v2\x11.codec.TypedValueR\belements\"\x93\x01\n" +
	"\vStructValue\x126\n" +
	"\x06fields\x18\x01 \x03(\v2\x1e.codec.StructValue.FieldsEntryR\x06fields\x1aL\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.codec.TypedValueR\x05value:\x028\x01\"X\n" +
	"\x16TypedStructValueLayout\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\x12*\n" +
	"\x06values\x18\x02 \x03(\v2\x12.codec.ValueLayoutR\x06values\"\x8c\x02\n" +
	"\rFlexibleValue\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.codec.ValueTypeR\x04type\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fstring_value\x18\x03 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vbytes_value\x18\x04 \x01(\fH\x00R\n" +
	"bytesValue\x12!\n" +
	"\vfloat_value\x18\x05 \x01(\x01H\x00R\n" +
	"floatValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x06 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vjson_string\x18\a \x01(\tH\x00R\n" +
	"jsonStringB\a\n" +
	"\x05value\"]\n" +
	"\x19FlexibleStructValueLayout\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\x12,\n" +
	"\x06values\x18\x02 \x03(\v2\x14.codec.FlexibleValueR\x06values*\xff\x02\n" +
	"\tValueType\x12\x1a\n" +
	"\x16VALUE_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eINT_VALUE_TYPE\x10\x01\x12\x15\n" +
	"\x11STRING_VALUE_TYPE\x10\x02\x12\x14\n" +
	"\x10BYTES_VALUE_TYPE\x10\x03\x12\x14\n" +
	"\x10FLOAT_VALUE_TYPE\x10\x04\x12\x16\n" +
	"\x12NUMERIC_VALUE_TYPE\x10\x05\x12\x1a\n" +
	"\x16BIG_NUMERIC_VALUE_TYPE\x10\x06\x12\x13\n" +
	"\x0fBOOL_VALUE_TYPE\x10\a\x12\x13\n" +
	"\x0fJSON_VALUE_TYPE\x10\b\x12\x14\n" +
	"\x10ARRAY_VALUE_TYPE\x10\t\x12\x15\n" +
	"\x11STRUCT_VALUE_TYPE\x10\n" +
	"\x12\x13\n" +
	"\x0fDATE_VALUE_TYPE\x10\v\x12\x17\n" +
	"\x13DATETIME_VALUE_TYPE\x10\f\x12\x13\n" +
	"\x0fTIME_VALUE_TYPE\x10\r\x12\x18\n" +
	"\x14TIMESTAMP_VALUE_TYPE\x10\x0e\x12\x17\n" +
	"\x13INTERVAL_VALUE_TYPE\x10\x0fB\x12Z\x10./internal/codecb\x06proto3"

var (
	file_internal_codec_codec_proto_rawDescOnce sync.Once
	file_internal_codec_codec_proto_rawDescData []byte
)

func file_internal_codec_codec_proto_rawDescGZIP() []byte {
	file_internal_codec_codec_proto_rawDescOnce.Do(func() {
		file_internal_codec_codec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_codec_codec_proto_rawDesc), len(file_internal_codec_codec_proto_rawDesc)))
	})
	return file_internal_codec_codec_proto_rawDescData
}

var file_internal_codec_codec_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_codec_codec_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_codec_codec_proto_goTypes = []any{
	(ValueType)(0),                    // 0: codec.ValueType
	(*ValueLayout)(nil),               // 1: codec.ValueLayout
	(*StructValueLayout)(nil),         // 2: codec.StructValueLayout
	(*TypedValue)(nil),                // 3: codec.TypedValue
	(*ArrayValue)(nil),                // 4: codec.ArrayValue
	(*StructValue)(nil),               // 5: codec.StructValue
	(*TypedStructValueLayout)(nil),    // 6: codec.TypedStructValueLayout
	(*FlexibleValue)(nil),             // 7: codec.FlexibleValue
	(*FlexibleStructValueLayout)(nil), // 8: codec.FlexibleStructValueLayout
	nil,                               // 9: codec.StructValue.FieldsEntry
}
var file_internal_codec_codec_proto_depIdxs = []int32{
	0,  // 0: codec.ValueLayout.header:type_name -> codec.ValueType
	1,  // 1: codec.StructValueLayout.values:type_name -> codec.ValueLayout
	4,  // 2: codec.TypedValue.array_value:type_name -> codec.ArrayValue
	5,  // 3: codec.TypedValue.struct_value:type_name -> codec.StructValue
	3,  // 4: codec.ArrayValue.elements:type_name -> codec.TypedValue
	9,  // 5: codec.StructValue.fields:type_name -> codec.StructValue.FieldsEntry
	1,  // 6: codec.TypedStructValueLayout.values:type_name -> codec.ValueLayout
	0,  // 7: codec.FlexibleValue.type:type_name -> codec.ValueType
	7,  // 8: codec.FlexibleStructValueLayout.values:type_name -> codec.FlexibleValue
	3,  // 9: codec.StructValue.FieldsEntry.value:type_name -> codec.TypedValue
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_internal_codec_codec_proto_init() }
func file_internal_codec_codec_proto_init() {
	if File_internal_codec_codec_proto != nil {
		return
	}
	file_internal_codec_codec_proto_msgTypes[2].OneofWrappers = []any{
		(*TypedValue_IntValue)(nil),
		(*TypedValue_StringValue)(nil),
		(*TypedValue_BytesValue)(nil),
		(*TypedValue_FloatValue)(nil),
		(*TypedValue_NumericValue)(nil),
		(*TypedValue_BigNumericValue)(nil),
		(*TypedValue_BoolValue)(nil),
		(*TypedValue_JsonValue)(nil),
		(*TypedValue_ArrayValue)(nil),
		(*TypedValue_StructValue)(nil),
		(*TypedValue_DateValue)(nil),
		(*TypedValue_DatetimeValue)(nil),
		(*TypedValue_TimeValue)(nil),
		(*TypedValue_TimestampValue)(nil),
		(*TypedValue_IntervalValue)(nil),
	}
	file_internal_codec_codec_proto_msgTypes[6].OneofWrappers = []any{
		(*FlexibleValue_IntValue)(nil),
		(*FlexibleValue_StringValue)(nil),
		(*FlexibleValue_BytesValue)(nil),
		(*FlexibleValue_FloatValue)(nil),
		(*FlexibleValue_BoolValue)(nil),
		(*FlexibleValue_JsonString)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_codec_codec_proto_rawDesc), len(file_internal_codec_codec_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_codec_codec_proto_goTypes,
		DependencyIndexes: file_internal_codec_codec_proto_depIdxs,
		EnumInfos:         file_internal_codec_codec_proto_enumTypes,
		MessageInfos:      file_internal_codec_codec_proto_msgTypes,
	}.Build()
	File_internal_codec_codec_proto = out.File
	file_internal_codec_codec_proto_goTypes = nil
	file_internal_codec_codec_proto_depIdxs = nil
}
